using System;
using System.IO;

namespace concatenateData
{
    internal class Program
    {
        static void Main(string[] args)
        {

            string firstName = Console.ReadLine();
            string lastName = Console.ReadLine();
            string age = Console.ReadLine();
            string town = Console.ReadLine();
            Console.WriteLine("You are " + firstName + " " + lastName + ", a " + age + "-year old person from " + town + ".");
        }
    }
    }
